# Generated by Django 5.2.9 on 2025-12-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='monthly_repayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
